### ISSUE TITLE
walk until you hit config

### ISSUE THREAD

**Issue by bcoe** [sindresorhus/pkg-conf#1]
Here's a problem I'm trying to solve:

In yargs I'd like to introduce the concept of a "yargs" stanza, which allows you to turn off some parsing features, etc. I'd like to have this configuration be part of the parser which I'm splitting into a separate module. I'd like the configuration to be read in from the parent library using yargs:

``` txt

---
    package.json <-- read me.
           node_modules
               ------  yargs
                                 package.json <-- has no yargs stanza, don't read.
                                 node_modules
                                           ---- yargs-parser
                                                       package.json <-- has no yargs stanza, don't read.
```

Basically I'd like to keep reading up directories until I hit a package.json with the appropriate stanza, similar to the behavior of `.npmrc`. Would it make sense to add this behavior to this library, as a configuration option? is this a different module?

**Comment by sindresorhus** [comment]
That won't work with npm@3 though, as `yargs-parser` and the users package might be on the same level. Instead I recommend you instead use a less fragile method of finding the parent config. Incidentally, I worked on a module for this a couple of weeks ago and finally took some time to polish it up and publish it: https://github.com/sindresorhus/parent-module See the `Tip` section. Just replace `read-pkg-up` with `pkg-conf`. Does that sound like a workable solution to you? Happy to discuss :)
