### ISSUE TITLE
There is an alternative way.

### ISSUE THREAD

**Issue by jimmywarting** [sindresorhus/pkg-conf#11]
npm already has something like config built in that don't get in the way of any package.json fields
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#config

```json
{
  "name": "some-package",
  "version": "1.0.0",
  "config": {
    "unicorn": {
      "rainbow": true
    }
  }
}
```

There isn't any need for looking up any package.json file or loading/reading a file sync or async and then parsing it...

you can access it from process env variables like so:
```js
// $> npm run start
console.log(process.env.npm_package_config_unicorn_rainbow) // true
```

**Comment by sindresorhus** [comment]
That only works when you run it from a npm script. And there's also a much higher chance of conflicts as it's not defined what `config` should contain, so some tools might namespace its properties while another one wouldn't. If you prefer the `config` way, you simply just don't use this package, but I personally prefer config to be under top-level namespaces.
