### ISSUE TITLE
Support `extends` for config.

### ISSUE THREAD

**Issue by nowells** [sindresorhus/pkg-conf#5]
I love `ava` and other packages you write! One challenge we face in my company is that we have a desire/need to centralize our default configuration across our organization (and allow projects to override/extend the defaults) so things like `ava` where we always have a default base configuration, it is a challenge to replicate this configuration across all repos and roll out changes/fixes.

It would be great to support something like `extends` (which packages like `nyc` package config support (https://www.npmjs.com/package/nyc#publish-and-reuse-your-nyc-configuration) to allow you to use 1 or more packages as default sources of configuration. I am happy to implement/test this feature in this package, but just wanted to see if you would be receptive to the idea?

Cheers!

**Comment by evocateur** [comment]
Tracing through `nyc` to `yargs` ends up [here](https://github.com/yargs/yargs/blob/a40cbc95277037b614c6a36b817ad31d4327fdae/lib/apply-extends.js#L19-L51), which is a bit ornate for this tightly-focused module. Given that you can already retrieve the [filepath](https://github.com/sindresorhus/pkg-conf/blob/9c1bba03f9fdd9449e9218eb03d1edc86acc0b28/index.js#L7) for a `pkg-conf` result, a lightweight wrapper for just the extends resolution and merging seems quite feasible.

**Comment by sindresorhus** [comment]
Closing as AVA has support for a separate file for config now, and like @evocateur said, for other use-cases, as wrapper could be made. Or just use something like `cosmiconfig` instead.
